# workflow is manually triggered

name: Create zip file for publishing

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      param:
        # Friendly description for the UI instead of 'param'
        description: 'Name of the zip file'
        default: 'SalesforceGPTExtension'
        required: true
        type: string

jobs:
  createZip:
    runs-on: ubuntu-latest

    steps:    
    - name: 'Checkout source code'
      uses: actions/checkout@main
    - name: copy files
      run: |
        echo ${{ github.repository }}
        mkdir ./dist
        mkdir ./dist/${{ inputs.param }}
        cp ./images ./dist/${{ inputs.param }}/images
        cp ./scripts ./dist/${{ inputs.param }}/scripts
        cp LICENSE ./dist/${{ inputs.param }}/LICENSE
        cp README.MD ./dist/${{ inputs.param }}/README.MD
        cp manifest.json ./dist/${{ inputs.param }}/manifest.json
        cp popup.css ./dist/${{ inputs.param }}/popup.css
        cp popup.html ./dist/${{ inputs.param }}/popup.html
    - name: zip files
      run: zip -r ${{ inputs.param }}.zip ./dist/${{ inputs.param }}
